TGT:=rapidjson
TGT_TYPE:=static_lib
SRC:=JSON_Document.cpp \
     JSON_Value.cpp \
     JSON_Values.cpp \
     JSON_Wrapper.cpp
TGT_DEPS:=
TEST_DRIVER_SRC:=
TEST_SRC:=
CLEANFILES:=
SUBDIRS:=
CFLAGS:=-I.
CPPFLAGS:=-fPIC
LDFLAGS:=

include ../../rules.mk
